---
- name: Enable Touch ID for sudo
  ansible.builtin.copy:
    src: "{{ role_path }}/files/sudo_local"
    dest: "/etc/pam.d/sudo_local"
    owner: root
    group: wheel
    mode: "0644"
  become: true

- name: Clean up some directories
  ansible.builtin.shell: |
    rm -rfv "{{ item }}" &>/dev/null
  changed_when: false
  become: true
  loop:
    # 'Empty the Trash on all mounted volumes and the main HDD...'
    - "/Volumes/*/.Trashes/*"
    - "{{ ansible_env.HOME }}/.Trash/*"
    # 'Clear System Log Files...'
    - "/private/var/log/asl/*.asl"
    - "/Library/Logs/DiagnosticReports/*"
    - "/Library/Logs/Adobe/*"
    - "{{ ansible_env.HOME }}/Library/Containers/com.apple.mail/Data/Library/Logs/Mail/*"
    - "{{ ansible_env.HOME }}/Library/Logs/CoreSimulator/*"
    # 'Clear Spotify Cache Files...'
    - "{{ ansible_env.HOME }}/Library/Application Support/Spotify/PersistentCache/Update/*.tbz"
    - "{{ ansible_env.HOME }}/Library/Caches/com.spotify.client/Data"
    # 'Clear Adobe Cache Files...'
    - "{{ ansible_env.HOME }}/Library/Application Support/Adobe/Common/Media Cache Files/*"
    # 'Cleanup iOS Applications...'
    - "{{ ansible_env.HOME }}/Music/iTunes/iTunes Media/Mobile Applications/*"
    # 'Remove iOS Device Backups...'
    - "{{ ansible_env.HOME }}/Library/Application Support/MobileSync/Backup/*"
    # 'Cleanup XCode Derived Data and Archives...'
    - "{{ ansible_env.HOME }}/Library/Developer/Xcode/DerivedData/*"
    - "{{ ansible_env.HOME }}/Library/Developer/Xcode/Archives/*"

- name: Clean up Homebrew cache
  ansible.builtin.shell: |
    brew cleanup -s &>/dev/null
    rm -rfv "$(brew --cache)" &>/dev/null
  changed_when: false
  become: true

- name: Install maintenance script
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/maintenance.sh"
    dest: "{{ maintenance_script_path }}"
    mode: "0755"
    owner: root
    group: wheel
  register: maintenance_script

- name: Create maintenance launchDaemon
  become: true
  ansible.builtin.template:
    src: "{{ maintenance_service }}.plist"
    dest: "/Library/LaunchDaemons/{{ maintenance_service }}.plist"
    owner: root
    group: wheel
    mode: "0644"
  register: maintenance_launch_daemon

- name: Kickstart maintenance LaunchDaemon
  become: true
  changed_when: false
  ansible.builtin.shell: |
    set -o pipefail
    launchctl unload -w /Library/LaunchDaemons/{{ maintenance_service }}.plist || true
    launchctl load -w /Library/LaunchDaemons/{{ maintenance_service }}.plist || true
  when: maintenance_launch_daemon.changed or maintenance_script.changed
