---
- name: Enable Touch ID for sudo
  ansible.builtin.copy:
    src: "{{ role_path }}/files/sudo_local"
    dest: "/etc/pam.d/sudo_local"
    owner: root
    group: wheel
    mode: "0644"
  become: true

- name: Clean up Homebrew cache
  ansible.builtin.shell: |
    brew cleanup -s &>/dev/null
    rm -rfv "$(brew --cache)" &>/dev/null
  changed_when: false
  become: true

- name: Install maintenance script
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/maintenance.sh"
    dest: "{{ maintenance_script_path }}"
    mode: "0755"
    owner: root
    group: wheel
  register: maintenance_script
  notify:
    - Kickstart maintenance LaunchDaemon

- name: Create maintenance launchDaemon
  become: true
  ansible.builtin.template:
    src: "{{ maintenance_service }}.plist"
    dest: "/Library/LaunchDaemons/{{ maintenance_service }}.plist"
    owner: root
    group: wheel
    mode: "0644"
  register: maintenance_launch_daemon
  notify:
    - Kickstart maintenance LaunchDaemon
