---
- name: Setup local machines
  hosts: localhost
  connection: local
  roles:
    - role: dependencies
      tags: deps
    - role: common
      tags: common
    - role: maintenance
      tags: clean
    - role: work
      tags: work
      when: work is defined

  handlers:
    - name: Kickstart maintenance LaunchDaemon
      become: true
      changed_when: false
      ansible.builtin.shell: |
        set -o pipefail
        launchctl unload -w /Library/LaunchDaemons/{{ maintenance_service }}.plist || true
        launchctl load -w /Library/LaunchDaemons/{{ maintenance_service }}.plist || true
