#!/bin/bash

# ==============================================================================
# = general                                                                    =
# ==============================================================================

set -o emacs

if [[ -f "$HOME/.shell_settings" ]]; then
  source "$HOME/.shell_settings"
fi

if [[ "$SHELL" == *"bash"* ]]; then
  # Set up fzf key bindings and fuzzy completion
  eval "$(fzf --bash)"
fi

# ==============================================================================
# = history                                                                    =
# ==============================================================================

# Disable per-terminal-session command history
SHELL_SESSION_HISTORY=0

# no duplicate entries
HISTCONTROL=ignoredups:erasedups
set completion-ignore-case on
