#!/bin/zsh

# ==============================================================================
# = general                                                                    =
# ==============================================================================

if [[ -f "$HOME/.shell_settings" ]]; then
  source "$HOME/.shell_settings"
fi

# enable emacs keybindings
bindkey -e

if [[ "$SHELL" == *"zsh"* ]]; then
  # Set up fzf key bindings and fuzzy completion
  source <(fzf --zsh)
fi

# ==============================================================================
# = history                                                                    =
# ==============================================================================

# Disable per-terminal-session command history
export SHELL_SESSIONS_DISABLE=1

setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS

# ==============================================================================
# = functions                                                                  =
# ==============================================================================

# Accepts one history line number as argument.
# Use `dc -1` to remove the last line.
dc () {
    local HISTORY_IGNORE="${(b)$(fc -ln $1 $1)}"
    fc -W
    fc -p $HISTFILE $HISTSIZE $SAVEHIST
    print "Deleted '$HISTORY_IGNORE' from history."
}
