---
- name: Install work dependencies
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ work_list }}"
  ignore_errors: true

- name: Clean up Bazel cache
  ansible.builtin.blockinfile:
    path: "{{ maintenance_script_path }}"
    marker: "# {mark} Remove Bazel cache"
    block: |
      trash_contents "/private/var/tmp/_bazel_{{ ansible_env.USER }}"
  become: true
  notify:
    - Kickstart maintenance LaunchDaemon
