---
- name: Template a file
  ansible.builtin.template:
    src: "{{ role_path }}/templates/.bazelrc"
    dest: "{{ ansible_env.HOME }}/.bazelrc"
    owner: "{{ ansible_env.USER }}"
    mode: "0644"

- name: Copy read-only files
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    mode: "0644"
  loop:
    - debug.logging.properties

- name: Install dependencies for Darwin
  ansible.builtin.include_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'
