---
- name: Set brew prefix
  ansible.builtin.set_fact:
    brew_prefix: "{{ '/opt/homebrew' if ansible_architecture == 'arm64' else '/usr/local' }}"

- name: Upgrade all Homebrew packages
  ansible.builtin.command: "{{ brew_prefix }}/bin/brew update --auto-update"

- name: Install dependencies
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ dependencies_list }}"

- name: Install mac specific dependencies
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - appcleaner
    - hiddenbar
    - karabiner-elements
    - logi-options+
    - reattach-to-user-namespace
    - rectangle
    - starship
    - stats

- name: Repair brew taps
  ansible.builtin.shell: |-
    brew tap --repair &>/dev/null
  changed_when: false
