---
- name: Upgrade all Homebrew packages
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- name: Install dependencies
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ dependencies_list }}"

- name: Install mac specific dependencies
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - karabiner-elements
    - logi-options+
    - starship
    - stats

- name: Repair brew taps
  ansible.builtin.shell: |-
    brew tap --repair &>/dev/null
  changed_when: false
