---
- name: Add additional stable repository from PPA and install its signing key on Ubuntu target
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
  become: true
  with_items:
    - ppa:neovim-ppa/stable
    - ppa:neovim-ppa/unstable

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ dependencies_list }}"

- name: Upgrade dependencies
  ansible.builtin.apt:
    upgrade: dist
  become: true

- name: Install debian specific packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - linux-headers-generic
    - build-essential
    - xclip
